package:
  name: NXazint
  version: "{{ SETUPTOOLS_SCM_PRETEND_VERSION }}"

source:
  path: ..

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - azint
    - setuptools_scm
    
  run:
    - python
    - azint
    
# test:
#   source_files:
#     - tests/*.py
#   requires:
#     - pytest
#   commands:
#     - pytest tests/

about:
  license: MIT
  license_file: ../LICENSE

 
